package com.champutils.antilag;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.*;
import java.util.*;

public final class AntiLagConfig {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final File FILE = new File("config/champutils/antilag.json");
    public static Data DATA = defaults();
    private AntiLagConfig() {}
    public static void load(){ try{ if(!FILE.getParentFile().exists()) FILE.getParentFile().mkdirs(); if(!FILE.exists()){ DATA=defaults(); save(); return;} try(FileReader r=new FileReader(FILE)){ DATA=GSON.fromJson(r,Data.class);} if(DATA==null) DATA=defaults(); normalize(); save(); }catch(Exception e){ DATA=defaults(); e.printStackTrace();}}
    public static void save(){ try{ if(!FILE.getParentFile().exists()) FILE.getParentFile().mkdirs(); try(FileWriter w=new FileWriter(FILE)){ GSON.toJson(DATA,w);} }catch(Exception e){e.printStackTrace();}}
    private static void normalize(){ Data d=defaults(); if(DATA.adminAlertPermission==null||DATA.adminAlertPermission.isBlank()) DATA.adminAlertPermission=d.adminAlertPermission; if(DATA.lagMachineKickMessage==null||DATA.lagMachineKickMessage.isBlank()) DATA.lagMachineKickMessage=d.lagMachineKickMessage; if(DATA.disabledDimensions==null) DATA.disabledDimensions=d.disabledDimensions; if(DATA.whitelistedAreas==null) DATA.whitelistedAreas=d.whitelistedAreas; if(DATA.discordWebhookUrl==null) DATA.discordWebhookUrl=""; if(DATA.scanIntervalSeconds<=0) DATA.scanIntervalSeconds=d.scanIntervalSeconds; if(DATA.cleanupIntervalMinutes<=0) DATA.cleanupIntervalMinutes=d.cleanupIntervalMinutes; if(DATA.cleanupWarningSeconds<=0) DATA.cleanupWarningSeconds=d.cleanupWarningSeconds; if(DATA.maxRemovalsPerScan<=0) DATA.maxRemovalsPerScan=d.maxRemovalsPerScan; if(DATA.violationDecayPerReset<0) DATA.violationDecayPerReset=d.violationDecayPerReset; if(DATA.kickScore<=0) DATA.kickScore=d.kickScore; if(DATA.tempBanScore<=0) DATA.tempBanScore=d.tempBanScore; }
    private static Data defaults(){ Data d=new Data(); d.enabled=true; d.detectLagMachines=true; d.autoPunishLagMachineSuspects=true; d.removeDetectedLagMachineEntities=true; d.alertAdmins=true; d.adminAlertPermission="champutils.antilag.alerts"; d.discordWebhookUrl=""; d.lagMachineKickMessage="You were kicked because the server detected a possible lag machine near you."; d.scanIntervalSeconds=5; d.maxPunishmentsPerScan=2; d.maxRemovalsPerScan=500; d.violationDecayPerReset=999; d.warnScore=20; d.kickScore=60; d.tempBanScore=100; d.tpsSpikeMsThreshold=80; d.requireTpsSpikeForPunishment=true;
        d.minecartDetectionEnabled=true; d.minecartClusterRadiusBlocks=8; d.minecartClusterThreshold=32; d.minecartPlayerAttributionRadiusBlocks=24;
        d.snowballDetectionEnabled=true; d.snowballWindowSeconds=10; d.snowballThrowThresholdPerWindow=70; d.snowballClusterRadiusBlocks=10; d.snowballClusterThreshold=50;
        d.genericEntityClusterDetectionEnabled=true; d.genericEntityClusterRadiusBlocks=8; d.genericEntityClusterThreshold=120;
        d.entityCleanupEnabled=true; d.cleanupIntervalMinutes=15; d.cleanupWarningSeconds=60; d.cleanupDroppedItems=true; d.cleanupWildPokemon=true; d.protectPokemonWithPersistenceRequired=true; d.protectPokemonWithCustomName=true; d.protectPokemonInBattle=true; d.protectPokemonWithOwnerOrStorage=true; d.disabledDimensions=new ArrayList<>(); d.whitelistedAreas=new ArrayList<>(); return d; }
    public static final class Data { public boolean enabled,detectLagMachines,autoPunishLagMachineSuspects,removeDetectedLagMachineEntities,alertAdmins; public String adminAlertPermission,discordWebhookUrl,lagMachineKickMessage; public int scanIntervalSeconds,maxPunishmentsPerScan,maxRemovalsPerScan,violationDecayPerReset,warnScore,kickScore,tempBanScore,tpsSpikeMsThreshold; public boolean requireTpsSpikeForPunishment; public boolean minecartDetectionEnabled; public int minecartClusterRadiusBlocks,minecartClusterThreshold,minecartPlayerAttributionRadiusBlocks; public boolean snowballDetectionEnabled; public int snowballWindowSeconds,snowballThrowThresholdPerWindow,snowballClusterRadiusBlocks,snowballClusterThreshold; public boolean genericEntityClusterDetectionEnabled; public int genericEntityClusterRadiusBlocks,genericEntityClusterThreshold; public boolean entityCleanupEnabled; public int cleanupIntervalMinutes,cleanupWarningSeconds; public boolean cleanupDroppedItems,cleanupWildPokemon,protectPokemonWithPersistenceRequired,protectPokemonWithCustomName,protectPokemonInBattle,protectPokemonWithOwnerOrStorage; public List<String> disabledDimensions; public List<Area> whitelistedAreas; }
    public static final class Area { public String name="trusted automation"; public String dimension="minecraft:overworld"; public int minX,minY,minZ,maxX,maxY,maxZ; }
}
